title: Missing In San Diego
description: A website for our GEO 583 group project!
theme: minima

# Add this section:
header_pages:
  - index.md
  - about.md
  - team.md
  - map1.md
  - map2.md
  - map3.md
  - map4.md
  - conclusion.md

# Make sure custom CSS is included
include:
  - assets/css

# Enable custom SASS processing (optional but clean)
sass:
  style: compressed

# Minima-specific settings (optional if you're overriding layout)
minima:
  skin: classic
  
